version: '3.4'

services:
  api_pokemon:
    image: ${DOCKER_REGISTRY-}apipokemon
    build:
      context: .
      dockerfile: Api_Pokemon/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: TeamPoke
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true
